### PR TITLE
added toroid footprints

### PR DESCRIPTION
**Pull request by jkriege2**
- based on a python script: https://github.com/pointhi/kicad-footprint-generator/pull/18
- PR for 3D models: https://github.com/KiCad/kicad-library/pull/927

2017-01-17 18_54_26-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-17 18_54_51-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-17 18_55_10-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-17 18_55_33-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

2017-01-17 18_52_05-3d viewer
2017-01-17 18_53_03-3d viewer

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Great footprints!

Once again we need to have a more concise naming scheme. See https://github.com/KiCad/Inductors_THT.pretty/pull/1

**Comment by SchrodingersGat** [comment]
@jkriege2  can you please adjust the script slightly - the positioning of RefDes on F.SilkS varies, and sometimes is under the pad

(Only for the `L_Toroid_Vertical` footprints)

**Comment by jkriege2** [comment]
will fix the Pad/REFDES-Problem ... but what do you mean by "the positioning of RefDes on F.SilkS varies" Can you give a quick screenshot?
Thanks,
JAN

**Comment by jkriege2** [comment]
the position should always be center-top

**Comment by SchrodingersGat** [comment]
a
b
c

**Comment by jkriege2** [comment]
Ahhh ... OK, also the CrtYd was wrong .. I'll bugfix in a minute:
2017-01-19 13_57_58-footprint editor no active library
2017-01-19 13_58_36-footprint editor no active library
2017-01-19 13_59_07-footprint editor no active library

**Comment by jkriege2** [comment]
Done!

**Comment by SchrodingersGat** [comment]
Thanks :)

A couple of notes (naming, again).

1. In https://github.com/KiCad/Inductors_THT.pretty/pull/1 we are using `L_CommonMode_` and here we are using `L_CommonModeChoke_`. I perfer `L_CommonMode_` are you OK to use that here too?
2. I don't think the word `series` as a suffix adds any information to the part name. e.g. `_Bourns_7500` is enough.

**Comment by jkriege2** [comment]
OK both fixed!

Thanks for spotting.
JAN

**Comment by SchrodingersGat** [comment]
Ok, looks great, thanks :)

**Pull request merged**
