### PR TITLE
added new axial inductor footprints (vertical+horizontal)

### PR DESCRIPTION
**Pull request by jkriege2**
- based on scripts: https://github.com/pointhi/kicad-footprint-generator/pull/18
- PR for 3D models: https://github.com/KiCad/kicad-library/pull/925

Note: There are more footprints than in the representative screenshots below:
2017-01-17 17_48_03-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-17 17_48_53-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-17 17_45_23-3d viewer

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Fantastic! I'll wait till we have discussed naming - https://github.com/KiCad/Inductors_THT.pretty/pull/1

BTW how are you making all these 3D models? They look really good! Are you scripting them?

**Comment by jkriege2** [comment]
Hi!

I'm doing parametrized models in FreeCad (i.e. a spreadsheet with the dimensions + parameter names and the use those params as variables in the models) and then output Python-scripts when making the footprints that I can paste in FreeCAD and then they export the new models. Here's an example of such a script (for examples of the models, see the `..._master.FCStd`-files with the 3D models):
```


 # L_Axial_L9.5mm_D4.0mm_P12.70mm_Horizontal_Fastron_SMCC
import FreeCAD
import os
import os.path

# d_wire
App.ActiveDocument.Spreadsheet.set('B4', '0.02')
App.ActiveDocument.recompute()
# L
App.ActiveDocument.Spreadsheet.set('B1', '9.5')
# d
App.ActiveDocument.Spreadsheet.set('B2', '4')
# d2
App.ActiveDocument.Spreadsheet.set('C2', '0')
# RM
App.ActiveDocument.Spreadsheet.set('B3', '12.7')
# shuntPinsRM
App.ActiveDocument.Spreadsheet.set('C3', '0')
# d_wire
App.ActiveDocument.Spreadsheet.set('B4', '0.7')
App.ActiveDocument.recompute()
doc = FreeCAD.activeDocument()
__objs__=[]
for obj in doc.Objects:	
    if obj.ViewObject.Visibility:
        __objs__.append(obj)

FreeCADGui.export(__objs__,os.path.split(doc.FileName)[0]+os.sep+"L_Axial_L9.5mm_D4.0mm_P12.70mm_Horizontal_Fastron_SMCC.wrl")
doc.saveCopy(os.path.split(doc.FileName)[0]+os.sep+"L_Axial_L9.5mm_D4.0mm_P12.70mm_Horizontal_Fastron_SMCC.FCStd")
print("created L_Axial_L9.5mm_D4.0mm_P12.70mm_Horizontal_Fastron_SMCC")


 # L_Axial_L9.5mm_D4.0mm_P15.24mm_Horizontal_Fastron_SMCC
import FreeCAD
import os
import os.path

# d_wire
App.ActiveDocument.Spreadsheet.set('B4', '0.02')
App.ActiveDocument.recompute()
# L
App.ActiveDocument.Spreadsheet.set('B1', '9.5')
# d
App.ActiveDocument.Spreadsheet.set('B2', '4')
# d2
App.ActiveDocument.Spreadsheet.set('C2', '0')
# RM
App.ActiveDocument.Spreadsheet.set('B3', '15.24')
# shuntPinsRM
App.ActiveDocument.Spreadsheet.set('C3', '0')
# d_wire
App.ActiveDocument.Spreadsheet.set('B4', '0.7')
App.ActiveDocument.recompute()
doc = FreeCAD.activeDocument()
__objs__=[]
for obj in doc.Objects:	
    if obj.ViewObject.Visibility:
        __objs__.append(obj)

FreeCADGui.export(__objs__,os.path.split(doc.FileName)[0]+os.sep+"L_Axial_L9.5mm_D4.0mm_P15.24mm_Horizontal_Fastron_SMCC.wrl")
doc.saveCopy(os.path.split(doc.FileName)[0]+os.sep+"L_Axial_L9.5mm_D4.0mm_P15.24mm_Horizontal_Fastron_SMCC.FCStd")
print("created L_Axial_L9.5mm_D4.0mm_P15.24mm_Horizontal_Fastron_SMCC")

# ...
```

**Comment by SchrodingersGat** [comment]
Huh, that's cool. Didn't realize FreeCAD could do that.

I am thinking of making a new repo for footprint and 3D model generators. Footprint generators would be based on the ones by @pointhi 

Having the scripts to generate 3D models would be great too :)

**Comment by SchrodingersGat** [comment]
Ok, happy with this :)

**Pull request merged**
