### PR TITLE
Added old inductors

### PR DESCRIPTION
**Pull request by jkriege2**
Here are all old inductors that are needed. A set of new ones will be added in a spearate PR ().
Here's a PR for the 3D models (only 2 ;-)  https://github.com/KiCad/kicad-library/pull/924

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
### Transformers

Can go here - https://github.com/KiCad/Transformers_THT.pretty

### Naming

These footprint names are getting very long. We need a better way (more concise) of naming them, I think.

e.g.

`L_CommonModeChoke_WuerthType-WE-CMB_Size-XL`

could become

`L_Common_Wuerth_WE-CMB_XL`

Also, for the toroid, `Diameter26mm` should be `D26` and the `horizontal` should be at the end.

**Comment by jkriege2** [comment]
I renamed the inductors that stay here ... the transformers I'll rename when moving them to the new libs! What do you think?

I kept the `_Horizontal`/`_Vertical` at the fron for the Toroids by purpose, as the use different size designators for horizontal and vertical mounting (e.g. for H the diameter is important, but for V the width/height on the PCB, as some of these have a small plastic-plate/box below them that ultimately determines their size.

Any better ideas?

JAN

**Comment by jkriege2** [comment]
PS: All the other PRs with new footprints follow a pretty solid system:
 - D+P for radial, round
 - W+H+P for radial, rectangular (possibly Px+Py instead of only P if pins under 45°
 - L+D+P+_Horizontal/_Vertical for axial inductors (as addendum I added the series name if I took it from a datasheet)
 - Horizontal+D+P for hor. toroids (here's the only exception that Horizontal is up front, see last comment)
 - Vertical+L+W+P for ver. toroids (here's the only exception that Horizontal is up front, see last comment)

Also: Note that this should match the standard we used for the new resistor/capacitor footprints!

**Comment by jkriege2** [comment]
thrid note: About the length I'm not too concerned ... I like having longer names that actually say what I get instead of cryptic short ones (then it's also easier to select something that MIGHT just match a new package ...)

**Comment by SchrodingersGat** [comment]
Hmm, ok, how about this:

The Weurth CMB series inductors are *by definition* Common Mode so I don't think that should be in the file name.

so for e.g. 

`L_Weurth_WE-CMB_XL` should suffice?

For more 'generic' parts we can deal with them as we go.

For this PR I think only the name change as above, such that the manufacturer name is second (after `L_`) as per the Inductors_SMD and many other libs.

**Comment by jkriege2** [comment]
But if we have `L_CommonMode_` a common-mode symbol could have an easy FPFilter `L*CommonMode*` which would match all usable footprints ... I would also say that we should name the common-mode SMD-chokes that way too ...

What do you think?
JAN

**Comment by SchrodingersGat** [comment]
Ok, that does make sense. 

So:

`L_CommonMode_WuerthType-WE-CMB-L.kicad_mod` 

becomes

`L_CommonMode_Wuerth_WE-CMB-L.kicad_mod`

* Remove *Type*
* Use `_` separator after manufacturer?

**Comment by jkriege2** [comment]
must have been a short brain-out ... that was a really strange name combination ;-)

SHould be fixed now.

OK?
JAN

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
